package modelo.pojo;
// Generated 01-10-2017 02:06:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Camposhansa generated by hbm2java
 */
public class Camposhansa  implements java.io.Serializable {


     private int idtblhansa;
     private String orden;
     private String corr;
     private String paciente;
     private String direccion;
     private String medico;
     private Integer edad;
     private Character sexo;
     private String sede;
     private Set histopatologias = new HashSet(0);
     private Set citologias = new HashSet(0);

    public Camposhansa() {
    }

	
    public Camposhansa(int idtblhansa, String orden) {
        this.idtblhansa = idtblhansa;
        this.orden = orden;
    }
    public Camposhansa(int idtblhansa, String orden, String corr, String paciente, String direccion, String medico, Integer edad, Character sexo, String sede, Set histopatologias, Set citologias) {
       this.idtblhansa = idtblhansa;
       this.orden = orden;
       this.corr = corr;
       this.paciente = paciente;
       this.direccion = direccion;
       this.medico = medico;
       this.edad = edad;
       this.sexo = sexo;
       this.sede = sede;
       this.histopatologias = histopatologias;
       this.citologias = citologias;
    }
   
    public int getIdtblhansa() {
        return this.idtblhansa;
    }
    
    public void setIdtblhansa(int idtblhansa) {
        this.idtblhansa = idtblhansa;
    }
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }
    public String getCorr() {
        return this.corr;
    }
    
    public void setCorr(String corr) {
        this.corr = corr;
    }
    public String getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(String paciente) {
        this.paciente = paciente;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getMedico() {
        return this.medico;
    }
    
    public void setMedico(String medico) {
        this.medico = medico;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public Set getHistopatologias() {
        return this.histopatologias;
    }
    
    public void setHistopatologias(Set histopatologias) {
        this.histopatologias = histopatologias;
    }
    public Set getCitologias() {
        return this.citologias;
    }
    
    public void setCitologias(Set citologias) {
        this.citologias = citologias;
    }




}


