package modelo.pojo;
// Generated 01-10-2017 02:06:43 PM by Hibernate Tools 4.3.1



/**
 * Catalogotipobitacora generated by hbm2java
 */
public class Catalogotipobitacora  implements java.io.Serializable {


     private int idtblcattipobitacora;
     private String descripcion;

    public Catalogotipobitacora() {
    }

    public Catalogotipobitacora(int idtblcattipobitacora, String descripcion) {
       this.idtblcattipobitacora = idtblcattipobitacora;
       this.descripcion = descripcion;
    }
   
    public int getIdtblcattipobitacora() {
        return this.idtblcattipobitacora;
    }
    
    public void setIdtblcattipobitacora(int idtblcattipobitacora) {
        this.idtblcattipobitacora = idtblcattipobitacora;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


