package modelo.pojo;
// Generated 01-10-2017 02:06:43 PM by Hibernate Tools 4.3.1



/**
 * Secuencetbl generated by hbm2java
 */
public class Secuencetbl  implements java.io.Serializable {


     private String alphaNumAutoIncrementCol;
     private String sampleDataCol;

    public Secuencetbl() {
    }

	
    public Secuencetbl(String alphaNumAutoIncrementCol) {
        this.alphaNumAutoIncrementCol = alphaNumAutoIncrementCol;
    }
    public Secuencetbl(String alphaNumAutoIncrementCol, String sampleDataCol) {
       this.alphaNumAutoIncrementCol = alphaNumAutoIncrementCol;
       this.sampleDataCol = sampleDataCol;
    }
   
    public String getAlphaNumAutoIncrementCol() {
        return this.alphaNumAutoIncrementCol;
    }
    
    public void setAlphaNumAutoIncrementCol(String alphaNumAutoIncrementCol) {
        this.alphaNumAutoIncrementCol = alphaNumAutoIncrementCol;
    }
    public String getSampleDataCol() {
        return this.sampleDataCol;
    }
    
    public void setSampleDataCol(String sampleDataCol) {
        this.sampleDataCol = sampleDataCol;
    }




}


