package modelo.pojo;
// Generated 01-10-2017 02:06:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblAudit generated by hbm2java
 */
public class TblAudit  implements java.io.Serializable {


     private int pkAudit;
     private String tableName;
     private char operation;
     private String oldValue;
     private String newValue;
     private Date updateDate;
     private String userName;

    public TblAudit() {
    }

	
    public TblAudit(int pkAudit, String tableName, char operation, Date updateDate, String userName) {
        this.pkAudit = pkAudit;
        this.tableName = tableName;
        this.operation = operation;
        this.updateDate = updateDate;
        this.userName = userName;
    }
    public TblAudit(int pkAudit, String tableName, char operation, String oldValue, String newValue, Date updateDate, String userName) {
       this.pkAudit = pkAudit;
       this.tableName = tableName;
       this.operation = operation;
       this.oldValue = oldValue;
       this.newValue = newValue;
       this.updateDate = updateDate;
       this.userName = userName;
    }
   
    public int getPkAudit() {
        return this.pkAudit;
    }
    
    public void setPkAudit(int pkAudit) {
        this.pkAudit = pkAudit;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public char getOperation() {
        return this.operation;
    }
    
    public void setOperation(char operation) {
        this.operation = operation;
    }
    public String getOldValue() {
        return this.oldValue;
    }
    
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }
    public String getNewValue() {
        return this.newValue;
    }
    
    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


